[project]
name = "moereport"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "accelerate>=1.10.0",
    "ipykernel>=6.30.1",
    "ipywidgets>=8.1.7",
    "torch>=2.8.0",
    "transformers>=4.55.2",
]
